BuildAndTest:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
    with:
      ref: ${{ github.head_ref }}
  - uses: actions/setup-node@v1
    with:
      node-version: "12.x"
  - name: Install Packages
    run: yarn install --frozen-lockfile
  - name: Build
    run: yarn build
  - name: Test
    run: yarn test
    
